### ISSUE TITLE
Issue found on mobile devices

### ISSUE THREAD

**Issue by Wronghand-hash** [rzkhosroshahi/zaman#100]
Dear Developer,

I am writing to report a bug that I have found in this awesome repository. Specifically, I am encountering an issue with the React datepicker module not selecting the correct date on phone displays. When I attempt to select a date using the datepicker on my mobile device, the calendar popup displays but the selected date is either not updated or is updated incorrectly. This issue is occurring consistently on multiple devices and on multiple screen sizes and only on phone size display.

I have attempted to troubleshoot this issue by checking the code for any errors or missing dependencies, but have been unable to identify a specific root cause. Additionally, I have tested the code on multiple devices with different screen sizes and resolutions, all of which are experiencing the same issue.

I would appreciate your assistance in resolving this issue as soon as possible, as it is impacting the functionality and performance of the application. Please let me know if you require any additional information or if there are any specific steps you would like me to take in order to help diagnose and repair the bug.

Thank you for your attention to this matter.

**Comment by rzkhosroshahi** [comment]
Hey there,

Thanks for reporting this issue.
However, I need more information from you. I would appreciate it if you could let me know the version of the package and what devices and browsers you have tested it on. You might also want to include the steps that can cause the problem and a screenshot, if possible.

**Comment by rzkhosroshahi** [comment]
As I checked, there is an issue in the `en` locale. The order of days In the week is not correct and this probably causes the problem. Basically in this case you always pick a day that is a day behind.

Just check out the new version beta [from here](https://codesandbox.io/s/issue-100-github-fdeg2w?file=/src/App.js) and let me know if your issue is solved.
