### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by eisa-rezaei** [rzkhosroshahi/zaman#103]
Issue in using package in nextjs App.

 "next": "13.1.6",
 "zaman": "^2.0.7"

![1402-02-30 00 28 12](https://github.com/rzkhosroshahi/zaman/assets/78264204/679918d7-270c-46d9-b84b-05d76d6cc522)

**Comment by behzad-ahmadi** [comment]
This error exists yet.
Jus crate a next app, import your package("zaman") in a component, run the project. It raises the error

> Hey Thank you for reporting this problem. I need more information, such as how can I reproduce the bug, and if you can provide me with a sandbox, it would help me with the debugging process.

**Comment by rzkhosroshahi** [comment]
Hi @behzad-ahmadi 

I already did this but I didn't get the error. Please create a repository and provide me with the link.

**Comment by HoFa1997** [comment]
Hi Mr.Khosroshahi
i have this error on Next.js (SyntaxError: Cannot use import statement outside a module)
when one time clear import line and run app and after that again import its work but at all hard reload get the error

i was test  :
const [hydrate, setHydrate] = useState(false)

useEffect(() => {
    setHydrate(true)
  }, [])

 {hydrate && (
          <CalendarProvider direction='ltr' locale='fa' round='x2'>
            <Calendar defaultValue={calendarValue} onChange={day => setCalendarValue(new Date(day))} />
          </CalendarProvider>
        )}
  
  but dosent work

**Comment by navidmadannezhad** [comment]
Hi dear.
same error here, seems the library doesn't support SSR yet. I also tried to load it using next/dynamic but still no results, gives me the below error:


`is not assignable to type 'ComponentType<{}>'`

**Comment by rzkhosroshahi** [comment]
Hey folks

For now, I don't have a plan for supporting SSR for this package. however, you can use _`use client`_ in the next apps to use the package.
