### ISSUE TITLE
onChange event on CalendarProvider range

### ISSUE THREAD

**Issue by mrmf0** [rzkhosroshahi/zaman#114]
hi, thanks a lot for stunning jalali date picker library. 
CalendarProvider range is more beautiful than select range by click on input so we preffered to use your CalendarProvider instead of DatePicker range, by the way you also provide an example like what i said on [codesandbox](https://codesandbox.io/s/new-version-date-picker-6eeepf) :

```typescript
<CalendarProvider locale="fa" round="x4" accentColor="#6374ae">
  <Calendar
    defaultValue={new Date()}
    onChange={(d) => console.log(d)}
    weekends={[6]}
    from={new Date()}
    to={new Date().setDate(new Date().getDate() + 7)}
    range
  />
</CalendarProvider>
``` 

but i think there is an issue that onChange event only returns first selected date but i hope when we proped range, onChange returns both date started and date ends, some thing like usual way that select date ranges works 
```typescript
<DatePicker onChange={(e) => console.log(e.from, e.to)} range />
```

 how we can use CalendarProvider to get full range dates?
 
 by the way is it possible to use this as one date click then select date range from clicked date till today?

**Comment by SalehMehrabani** [comment]
The calendar is better for some applications however in range mode the component only returns the start date. It would be better to return both values in range mode.

**Comment by rzkhosroshahi** [comment]
Hi @mrmf0 

I hope you guys are doing well. I've looked at your codesandbox example. There is no problem with the package when you are using range datepicker/calendar you can just simply receive **_from_** and _**to**_ dates by two parameters like this: **`onChange={(from, to) => console.log(from, to)}`**. have you tried this before?

**Comment by mrmf0** [comment]
hi @rzkhosroshahi
I don't know why I feel that I tried this method before and it didn't work, even maybe I didn't try it.

thanks a lot

**Comment by rzkhosroshahi** [comment]
[114](https://github.com/rzkhosroshahi/zaman/tree/114-onchange-event-on-calendarprovider-range)

**Comment by rzkhosroshahi** [comment]
[v2.1.0](https://github.com/rzkhosroshahi/zaman/releases/tag/v2.1.0) just released this issue should be fixed by upgrading zaman.
