### ISSUE TITLE
would like to change the format from mm-dd-yy to dd-mm-yyyy

### ISSUE THREAD

**Issue by lakshmidurgad** [rzkhosroshahi/zaman#120]
**Describe the bug**
By using Zaman date picker, the default date format is mm-dd-yy, but as per our requirement the format should be dd-mm-yyyy, please help me in modifying the format.

**Expected behavior**
the format should be dd-mm-yyyy

**Screenshots**
<img width="204" alt="image" src="https://github.com/rzkhosroshahi/zaman/assets/149652793/8c4bb042-e152-4428-9c0c-76b58768d65b">

**Comment by rzkhosroshahi** [comment]
[120](https://github.com/rzkhosroshahi/zaman/tree/120-would-like-to-change-the-format-from-mm-dd-yy-to-dd-mm-yyyy)

**Comment by lakshmidurgad** [comment]
Thank you for the update, currently we have node version 18 in local, but in server the version is 16. please let us know whether the date picker is supported by node version 16.

**Comment by rzkhosroshahi** [comment]
> Thank you for the update, currently we have node version 18 in local, but in server the version is 16. please let us know whether the date picker is supported by node version 16.

Unfortunately, I don't have a support plan for this node version. It's mainly because of all the dependencies we have. I hope you find another solution.
