### ISSUE TITLE
'day' and 'to' values in that onChange callback function have same value (range props is true)

### ISSUE THREAD

**Issue by MohammadShahheydar** [rzkhosroshahi/zaman#125]
hi . this is my code
``
<CalendarProvider locale={'fa'} direction={'rtl'} round={'x2'}>
                            <Calendar
                                className={'calendar'}
                                range
                                onChange={(day: Date, to?: Date) => {
                                    console.log(day)
                                    console.log(to)
                                }}/>
                        </CalendarProvider>
``

but when calendar changes dat and to is the same

log result => 
day => Tue Nov 28 2023 22:28:56 GMT+0330 (Iran Standard Time)
to => Tue Nov 28 2023 22:28:56 GMT+0330 (Iran Standard Time)

**Comment by rzkhosroshahi** [comment]
Hey Mohammad,

This issue raised by someone else and now I'm working on it here is the [link](https://github.com/rzkhosroshahi/zaman/issues/114). I'm gonna close your issue you can follow other one.

Thanks for reporting the issue.

**Comment by rzkhosroshahi** [comment]
> hi . this is my code `<CalendarProvider locale={'fa'} direction={'rtl'} round={'x2'}> <Calendar className={'calendar'} range onChange={(day: Date, to?: Date) => { console.log(day) console.log(to) }}/> </CalendarProvider>`
> 
> but when calendar changes dat and to is the same
> 
> log result => day => Tue Nov 28 2023 22:28:56 GMT+0330 (Iran Standard Time) to => Tue Nov 28 2023 22:28:56 GMT+0330 (Iran Standard Time)


[v2.1.0](https://github.com/rzkhosroshahi/zaman/releases/tag/v2.1.0) just released your issue should be fixed by upgrading zaman.
