### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module in next.js

### ISSUE THREAD

**Issue by saman-irancounter** [rzkhosroshahi/zaman#132]
**Describe the bug**

**Executable links**
use  [codesandbox](https://codesandbox.io/dashboard) or any tool that can reproduce the issue.

**To Reproduce**
4. See the error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Comment by rzkhosroshahi** [comment]
duplicate #103
