### ISSUE TITLE
Disable Keyboard when component opens on mobile.

### ISSUE THREAD

**Issue by theMasix** [rzkhosroshahi/zaman#25]
Hello. When I open the component by clicking the Date box, the Mobile Keyboard will opens too! It's a bug I think. Although you use an input to show the date that have picked, but you should disable the keyboard when date box is opened.

**Comment by rzkhosroshahi** [comment]
Hey thanks
I'm working on a new version of this package, but I don't know when it will be available.
anyway If you want to implement it, feel free to open a PR ☺️

**Comment by rouzbeh-hatamy** [comment]
thanks for this awesome package ✔✔✔❤. and I'm looking forward for this Improvement too
