### ISSUE TITLE
Hot to customize datepicker?

### ISSUE THREAD

**Issue by buglessir** [rzkhosroshahi/zaman#26]
I've installed this package, but I didn't find any prop to change theme or disable unnecessary buttons like time picker (watch popup). Where can I find theme names lists or resize the font-size?
Thanks

**Comment by rzkhosroshahi** [comment]
Hello
There is not themes you can define your own theme. look at this [default theme ](https://github.com/rzkhosroshahi/react-jalali-datepicker/blob/master/src/theme.ts).
and if you looking for other available features you can see all of theme in the document

**Comment by theMasix** [comment]
Disabling timePicker: #24 
And all default theme values are [here](https://github.com/rzkhosroshahi/react-jalali-datepicker/blob/master/src/theme.ts)

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
