### ISSUE TITLE
Change date value programmatically !

### ISSUE THREAD

**Issue by HamedMoghadasi** [rzkhosroshahi/zaman#27]
Hello,
I need to change the date value programmatically, is there any solution!

Thanks.

**Comment by rzkhosroshahi** [comment]
Hey,
What your means exactly of (programmatically)?

**Comment by HamedMoghadasi** [comment]
Besides datepicker I have a timeline slider. when this slider change I wanna update datepicker input value.

**Comment by rzkhosroshahi** [comment]
> Besides datepicker I have a timeline slider. when this slider change I wanna update datepicker input value.

Yes, it seems the DatePicker component's value not getting update when it changed.
I'll solve this issue as soon as possible. Thanks for reporting this issue 🙂
If you want to implement it, feel free to open a PR  🙂

**Comment by HamedMoghadasi** [comment]
Thank you for your response 👍

**Comment by MohammadAzimi** [comment]
please close the issue if it's fixed 🙏
@rzkhosroshahi @HamedMoghadasi
