### ISSUE TITLE
set custom theme

### ISSUE THREAD

**Issue by mzhb80** [rzkhosroshahi/zaman#47]
Hello . how can i define my custom theme at 'theme' attribute . can you show me an example . thanks

**Comment by mohammadsadeghforoughi** [comment]
Hello, I think you can create a theme by creating a theme file with your own theme properties.
check [it](https://github.com/rzkhosroshahi/react-jalali-datepicker/blob/master/src/theme.ts)

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
