### ISSUE TITLE
how can set deafult value ?

### ISSUE THREAD

**Issue by fariborz0015** [rzkhosroshahi/zaman#52]
hi ,
how can i set a default Value for showing in input  ?  or set null default  value for input ?

sorry about my eng .. ):

**Comment by gprsm** [comment]
نویسندگان توی یک بخش هایی خیلی کم دقتی کردن. با اینکه استایل این دیت پیکر خیلی زیباست اما من کلاً عطایش رو به لقائش بخشیدم. خیلی توی مثلاً مقدار پیش فرض، مقدار خروجی و ..... کم کاری شده

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
