### ISSUE TITLE
why not use props open?

### ISSUE THREAD

**Issue by mojtabajahannia** [rzkhosroshahi/zaman#60]
hi @rzkhosroshahi 
thank you for useful calendar.
but i'm problem and that, not use props open in `<DatePicker open={true} />`.
Do i use right?

**Comment by shafazadeh** [comment]
it s my problem too.

**Comment by club9822** [comment]
for now, use ref
```
const ref = useRef();
<DatePicker ref={ref} />

ref.current.toggleModalOpen();
```

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
