### ISSUE TITLE
Change year

### ISSUE THREAD

**Issue by MohammadMahdiDoroud** [rzkhosroshahi/zaman#64]
I need to change year, for example I need to choose year 1380,

**Comment by mortezashojaei** [comment]
+1

**Comment by MB-KING** [comment]
+1

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
