### ISSUE TITLE
stream package is not working after webpack 5

### ISSUE THREAD

**Issue by xXm5aXx** [rzkhosroshahi/zaman#68]
i changed `stream` package in `/dist/index.module.js` with `stream-browserify` so it worked.

**Comment by MohammadXroid** [comment]
In case anyone comes across this issue, first install npm i stream-browserify dependency, then go to node_modules/jalali-react-datepicker/dist/index.module.js and from the first line, replace "stream" with "stream-browserify" and the the error should be gone.
