### ISSUE TITLE
ERROR. in the link preview

### ISSUE THREAD

**Issue by nafasebra** [rzkhosroshahi/zaman#72]
#### Hi. I see an issue in link preview (data-picker preview)

You see an error about routing when load pages and don't see data-picker when resolve this error

The error: 
![Capture](https://user-images.githubusercontent.com/74317517/194739378-895ed196-ee8c-4137-bfcd-9b6e668788cd.PNG)

The page when solved the error
![display](https://user-images.githubusercontent.com/74317517/194739399-d9ff144d-9399-447d-9367-7a451a9d6a93.PNG)

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
