### ISSUE TITLE
Two date picker when datepicker opens

### ISSUE THREAD

**Issue by PouyaKrm** [rzkhosroshahi/zaman#73]
Hi.
When I click on the date picker, it contains two date pickers that are under each other

**Comment by Ehsan-heydari** [comment]
Hi ,Me too 
Did you find a way?

**Comment by ahmad-shoja** [comment]
> Hi. When I click on the date picker, it contains two date pickers that are under each other

Hi, can you explain how its happening? how can I to reproduce the bug?

**Comment by PouyaKrm** [comment]
The first time I open the date picker, It produces this bug. 
After it gets closed and reopened again, it appears normal.

**Comment by rzkhosroshahi** [comment]
Hey 👋🏻
Here's an announcement that a new version of the module has just been released. Since this issue is related to the older version, I have closed it. I would appreciate your feedback on the new version.
