### ISSUE TITLE
onChange returns wrong Date

### ISSUE THREAD

**Issue by mahmudipur** [rzkhosroshahi/zaman#81]
value argument that received from onChange call back function is returning the last selected date and it's not correct 👎🏼

**Comment by rzkhosroshahi** [comment]
Hey @mahmudipur 

Could you please provide me with the executable code so I can test it?  (like [codesandbox](https://codesandbox.io/dashboard))

**Comment by mahmudipur** [comment]
here we go with this [codesandbox](https://codesandbox.io/s/new-version-date-picker-forked-mt0qb2?file=/src/App.tsx)

today is Apr 4 (15 Farvardin) and when you click on Apr 3 (14 Farvardin) you will see Apr 4 has logged in console.

your datepicker is way much better than the other datepickers and this should not happen in a perfect package like this 😉

**Comment by mahmudipur** [comment]
here we go with this [codesandbox](https://codesandbox.io/s/new-version-date-picker-forked-mt0qb2?file=/src/App.tsx)

today is Apr 4 (15 Farvardin) and when you click on Apr 3 (14 Farvardin) you will see Apr 4 has logged in console.

your datepicker is way much better than the other datepickers and this should not happen in a perfect package like this 😉

**Comment by rzkhosroshahi** [comment]
@mahmudipur

Thanks for reporting this issue. It was crucial. 
Now, you can install the latest version of the module and you'll be fine.

**Comment by mahmudipur** [comment]
yeah I checked it and it's working quite fine thanks a lot 🙏

**Comment by mrvcoder** [comment]
thanks for the datepicker !
why when I log the value instead of the input value which is like this format : YYYY/MM/DD 
it is printing like this : 
Tue Apr 16 2024 21:09:34 GMT+0330 (Iran Standard Time)

how can I get input value ?
